### ISSUE TITLE
Add /r command, or remove /msg completely to let other plugins (eg. Essentials) handle it.

### ISSUE THREAD

**Issue by jan64** [mc-server/Core#118]
I'm not sure which one of those is a better choice.

**Comment by STRWarrior** [comment]
Another option is to load Essentials before Core. That should work as well. You can do that in the settings.ini file by putting `Plugin=Essentials` before `Plugin=Core`.

**Comment by STRWarrior** [comment]
Also, I don't think a plugin should remove a feature just because another plugin has that feature too.

**Comment by madmaxoft** [comment]
There is a hook that is called when a player issues a command; Essentials could use that hook to prevent the Core from even seeing the command. Somewhat hackish, but I think it's the best solution so far (unless we want to move the entire functionality over to the Core, which might be a good idea as well)

**Comment by tonibm19** [comment]
I'm not happy if I have to remove Essentials features (already removed more than 5 commands), but as /msg is an important command, /r could be implemented into core and /msg removed from Essentials

**Comment by STRWarrior** [comment]
But loading Essentials before should fix the problem altogether right?

**Comment by tonibm19** [comment]
Yes, it should. 
Then there is still the error message which appears if a command is asigned to more than 1 plugin.

**Comment by madmaxoft** [comment]
Consider it not removing a feature. It's more like moving the feature from one plugin to another. This way it's even gonna be accessible to a lot more people by default.

**Comment by tonibm19** [comment]
Then, move /r to Core?

**Comment by madmaxoft** [comment]
Yes

**Comment by jonfabe** [comment]
So peanut gallery chiming in here, Core is already a fairly large plugin code wise, why not consider splitting all the Chat commands currently in Core off into a separate default plugin, say something like Core:Chat? That way if people want to use a different chat handler they can just disable the Core:Chat plugin?

**Comment by madmaxoft** [comment]
Do you think there will be a different chat plugin? I find it highly unlikely.

**Comment by tonibm19** [comment]
Moved /r into core

**Comment by jonfabe** [comment]
Eh, I know there was for bukkit/spigot and given `/r` was a part of a
different plugin already for MCServer it seems likely that someone at some
point might get the idea that they want their own chat system rather then
the default for whatever reason (say adding separate chat channels like
towny, for instance, which had town/nation channels in addition to the
global channel).

**Comment by tonibm19** [comment]
That is actually possible with a plugin.
You just need to loop throught all players, and if they match the conditions, send them the message

**Comment by jonfabe** [comment]
@tonibm19 I know, I was just giving an example for @madmaxoft as to why another plugin writer might create their own chat system and want to disable the chat commands in Core. At any rate, its nothing that has to be addressed currently, but is something to keep in mind for the future.

**Comment by jan64** [comment]
Thanks.
Imo, splitting core into more than one plugin sounds good, but would take some time (and possibly create a bit of confusion).
