### ISSUE TITLE
/plugins command is broken

### ISSUE THREAD

**Issue by mathias-gh** [mc-server/Core#133]
After updating MCServer to the latest version, the /plugins command has stopped working.

This error appears in the console:
```
[13:59:03] Stack trace:
[13:59:03]   [C](-1): GetAllPlugins
[13:59:03]   Plugins/Core/plugins.lua(3): (no name)
[13:59:03] Stack trace end
[13:59:04] PluginManager:GetAllPlugins() is no longer available, use cPluginManager:ForEachPlugin() instead
```

**Comment by madmaxoft** [comment]
Are you using the latest Core version? It has been updated after the API change.

**Comment by mathias-gh** [comment]
Yes, Core was updated at the same time. I updated about an hour ago.

I looked at the source code here on GitHub, and it seems like PluginManager:GetAllPlugins() still is used in plugins.lua. The file was last updated on Jul 27, 2014.

**Comment by NiLSPACE** [comment]
You forgot to update the in-game command: https://github.com/mc-server/Core/blob/master/plugins.lua#L3

**Comment by madmaxoft** [comment]
Ah, I had no idea we had an in-game command, too.

**Comment by madmaxoft** [comment]
There, a fix and an enhancement. Now you can filter the output by plugin status (`loaded`, `unloaded`, `error`, `disabled`, `notfound`, `all`)
