### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by s32ialx** [mc-server/Core#141]
These types of permissions do not have a / command attached.

core.drop.item  - Allows for revoking a rank from dropping items (IE Players in creative mode)  thus they must destroy it to rid themselves of it (or if NPC shops are made then could be sold to it)

not sure how hard that would be to implement. but noting the default ranks are Default and VIP (if you let VIP players spawn in items then whats the point of having a difference)

Obviously you have to take blocks in to account so maybe core.drop.item.id to allow certain blocks to be dropped or even not droped or just core.drop.itemid

Edit: Maybe even a command that will let us take a specific item from a player 

/iTake ID, player, amount

Also the proposed alias at least to /give to also become /iGive giving you 

iEnchant, iGive, iTake (I know iEnchant is for self)

**Comment by madmaxoft** [comment]
This should most likely go into the Essentials plugin, since it's not vanilla behavior

**Comment by s32ialx** [comment]
ahh yeah I guess you are right I remember that now oops!

**Comment by Rakete1111** [comment]
You should close it then
