### ISSUE TITLE
Whitelist crashing the Server

### ISSUE THREAD

**Issue by Aggroblut** [mc-server/Core#142]
1. join the game
2. leave the game
3. Console: whitelist on
4. joining -> Server crash

**Comment by madmaxoft** [comment]
Is there anything specific in the server log, or in the console? Could you provide as much information based on these two guides (windows / linux):
http://forum.mc-server.org/showthread.php?tid=400
http://forum.mc-server.org/showthread.php?tid=631
Thanks.

**Comment by Aggroblut** [comment]
I'm really sorry but there is not log, no crashfile nothing. Also TaskInfo cant create a dump.

**Comment by tigerw** [comment]
Fixed by 291370e367f9c51f894ff132860ac2b55727181f
