### ISSUE TITLE
Remove some commands and move to Essentials

### ISSUE THREAD

**Issue by tonibm19** [mc-server/Core#143]
Related to https://github.com/mc-server/Essentials/issues/23
I'll write here a list of the commands I plan to move:
/fly
/locate
/me
/top
/tpa /tpa here (and /tpaccept)
/tpdeny
/tphere or /bring
/vanish

Then there are commands such as /tps which are not in vanilla but I think there are enough important to keep in Core.

I think it would also be good to move Essentials /xp into Core, as its in vanilla.

What do you think?

**Comment by jan64** [comment]
Will the essentials be distributed with mcserver (in a disabled state), or will it be a separate download?

**Comment by NiLSPACE** [comment]
I think we'll go with a separate download.

**Comment by madmaxoft** [comment]
I think it will be so essential that we'd package it with the server, same as Core is now.
Especially if we decide that ranking commands and webadmin is not vanilla and should be moved to Essentials.

**Comment by tonibm19** [comment]
ranking and webadmin need to be kept on core, they are needed for the server.

**Comment by madmaxoft** [comment]
It depends on the view. If we don't want anything non-vanilla in the Core, then we should move them to Essentials, too.

**Comment by NiLSPACE** [comment]
It might be usefull to implement those commands directly in the server. Then you can always change the ranks even if Core or Essentials isn't installed.

**Comment by bearbin** [comment]
Keeping the ranking system and webadmin in core would make the most sense for me. Core is vanilla commands and essentials for the server to work. (Rank commands are necessary for the permission system).

**Comment by tonibm19** [comment]
I'll start with this
